default_context:
  project_name: 'websocket_backend'
  project_slug: 'websocket_backend'
  domain_main: 'websocket_backend.com'
  domain_staging: 'stag.websocket_backend.com'
  docker_swarm_stack_name_main: 'websocket_backend-com'
  docker_swarm_stack_name_staging: 'stag-websocket_backend-com'
  secret_key: 'changethis'
  first_superuser: 'admin@websocket_backend.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.websocket_backend.com", "https://stag.websocket_backend.com", "https://websocket_backend.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@websocket_backend.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@websocket_backend.com'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'websocket_backend.com'
  traefik_constraint_tag_staging: 'stag.websocket_backend.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  _copy_without_render: [backend/app/app/email-templates/**]
  _template: ./
